version: "3"
services:
  db:
    image: mysql
    container_name: mysql
    #restart: always
    environment:
      - MYSQL_DATABASE=borsa_treball
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=
    ports:
      - 3306:3366
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD:
  backend:
    image: springboot_fct_app:snapshot2
    container_name: spring-backend
    ports:
      - 8070:8070
    depends_on:
      - db
#docker-compose up -d