version: "3"
services:
  db:
    image: mysql
    container_name: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=borsa_treball
      - MYSQL_USER=fct
      - MYSQL_PASSWORD=fct
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
#services:
#  myservice:
#    restart: "no"

#    build: .

#    ports:
#      - 8070:8080/tcp