version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=borsa_treball

    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  backend:
    depends_on:
      - mysqldb
    image: iticbcndam13/projecte1:mysql
    ports:
      - 8080:8070
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysqldb:db
    ports:
      - 8000:80
    environment:
      - PMA_HOST=mysqldb
      - MYSQL_ROOT_PASSWORD=1234
volumes:
  db:
#docker-compose up -d
